# For help and tutorials, visit https://circleci.com/docs/
# For internal documentation visit https://enturas.atlassian.net/wiki/spaces/ESP/pages/580026490/CircleCI
version: 2.1

orbs:
  #  slack: circleci/slack@1.0.0
  docker-publish: circleci/docker-publish@0.1.7
  node: circleci/node@1.1.6

references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

aliases:
  - &create-image-version
    name: Create new image version and store to env var and as file in workspace
    command: |
      echo "export VERSION=$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)"  >> $BASH_ENV
      echo "$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)" > version
      cp ./version /tmp/workspace
  - &read-image-version
    name: Read new image version from workspace
    command: |
      echo "export VERSION=$(cat /tmp/workspace/version)" >> $BASH_ENV
  - &tag-git-version
    name: Tag git commit with build version and push to github
    command: |
      git config --global user.email "circleci@entur.no"
      git config --global user.name "circleci"
      git tag $VERSION
      git push origin $VERSION

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16.1'
    steps:
      - *attach_workspace
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          cache-version: v4
          steps:
            - run: yarn
      - run:
          name: 'Run tests'
          command: yarn test
      - run:
          name: 'Create production build'
          command: yarn build
      - run:
          name: 'Persist built files'
          command: |
            set -exu
            mv build /tmp/workspace/
            mv node_modules /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build/*
            - node_modules/*
  tag:
    docker:
      - image: google/cloud-sdk:alpine
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - *attach_workspace
      - checkout
      - run: *create-image-version
      - run: *tag-git-version
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./version

workflows:
  'Build Pipeline':
    jobs:
      - build
      - tag:
          context: global
          filters:
            branches:
              only: master
      - docker-publish/publish:
          context: global
          filters:
            branches:
              only: master
          requires:
            - build
            - tag
          image: $CIRCLE_PROJECT_REPONAME
          tag: $VERSION
          registry: $DOCKER_REGISTRY
          before_build:
            - *attach_workspace
            - run: *read-image-version
            - run: |
                mv /tmp/workspace/build .
                mv /tmp/workspace/node_modules .
