apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
      kubernetes.io/ingress.class: traefik
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
spec:
    rules:
    - host: {{ .Release.Name }}-{{ .Release.Namespace }}{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.externalPort }}
